"""Initialize a project-specific RAG knowledge base."""

from __future__ import annotations

import argparse
from pathlib import Path

from common import append_log, ensure_rag_dirs

TEMPLATE_CONTENT = """# Source Page Template

This template was generated by `rag-init`. Customize fields as needed.

```yaml
---
type: source
created: YYYY-MM-DD
last_updated: YYYY-MM-DD
title: ""
authors: []
year: ""
venue: ""
doi: ""
arxiv: ""
pdf: ""
{tag_fields}
---
```

{body_fields}
"""

VOCABULARY_HEADER = """# Controlled Vocabulary

Generated by `rag-init`. This file is the schema authority for RAG dimension tags.

```yaml
vocabulary:
{axes}
```

## Rules

- Unknown tags must not be invented silently during ingest.
- Use `uncategorized` only as a temporary placeholder.
- Propose a vocabulary diff and wait for user approval before adding tags.
"""

INDEX_CONTENT = """# RAG Index

## Navigation

- [Vocabulary](vocabulary.md)
- [Source template](template.md)
- [References manifest](references.bib)
- [Operation log](log.md)

## Knowledge areas

- [Sources](summary/sources/)
- [Synthesis](summary/synthesis/)
{dimension_links}

## Source pages

<!-- AUTO:SOURCES:BEGIN -->
No source pages indexed yet.
<!-- AUTO:SOURCES:END -->
"""

SKILL_CONTENT = """# RAG Knowledge Base

This directory is the Markdown-first research knowledge layer for the Vibe Research Pipeline.

## Entry points

- [Index](index.md)
- [Vocabulary](vocabulary.md)
- [Source template](template.md)
- [Operation log](log.md)
- [References manifest](references.bib)

## Layout

- `reference/` stores raw materials such as PDFs, BibTeX, Zotero exports, and import artifacts.
- `summary/sources/` stores one structured source page per paper or research material.
- `summary/synthesis/` stores cross-source synthesis, consensus, disputes, and note-derived knowledge.
- `summary/<dimension>/` directories are generated by initialization from project-specific dimensions.

Use the skills in `.claude/skills/rag*` for operations. Keep project knowledge in this directory, not in `CLAUDE.md`.
"""


def main() -> int:
    parser = argparse.ArgumentParser(description="Initialize RAG knowledge base")
    parser.add_argument("--rag-dir", default="RAG")
    parser.add_argument("--dimensions", default="", help="Comma-separated dimension names, e.g. methods,models,datasets")
    parser.add_argument("--vocabulary", default="", help="Comma-separated vocabulary axis names")
    parser.add_argument("--template-fields", default="metadata,summary,key findings,limitations,links", help="Comma-separated source page body fields")
    args = parser.parse_args()

    rag_dir = Path(args.rag_dir).resolve()
    dimensions = [d.strip() for d in args.dimensions.split(",") if d.strip()]
    vocab_axes = [v.strip() for v in args.vocabulary.split(",") if v.strip()]

    ensure_rag_dirs(rag_dir, dimensions)

    # template.md
    tag_lines = "\n".join(f'{dim}: []' for dim in dimensions)
    body_lines = "\n".join(f"## {field.strip()}" for field in args.template_fields.split(",") if field.strip())
    (rag_dir / "template.md").write_text(
        TEMPLATE_CONTENT.format(tag_fields=tag_lines, body_fields=body_lines),
        encoding="utf-8",
    )

    # vocabulary.md
    vocab_axes_lines: list[str] = []
    for axis in vocab_axes:
        vocab_axes_lines.append(f"  {axis}:")
        vocab_axes_lines.append(f'    uncategorized:')
        vocab_axes_lines.append(f'      canonical: "Uncategorized"')
        vocab_axes_lines.append(f"      aliases: []")
    (rag_dir / "vocabulary.md").write_text(
        VOCABULARY_HEADER.format(axes="\n".join(vocab_axes_lines)),
        encoding="utf-8",
    )

    # index.md
    dim_links = "\n".join(f"- [{d}](summary/{d}/)" for d in dimensions)
    (rag_dir / "index.md").write_text(
        INDEX_CONTENT.format(dimension_links=dim_links),
        encoding="utf-8",
    )

    # SKILL.md
    (rag_dir / "SKILL.md").write_text(SKILL_CONTENT, encoding="utf-8")

    # log.md
    if not (rag_dir / "log.md").exists():
        (rag_dir / "log.md").write_text("# RAG Operation Log\n\n", encoding="utf-8")

    # references.bib
    if not (rag_dir / "references.bib").exists():
        (rag_dir / "references.bib").write_text("% RAG shared references manifest\n", encoding="utf-8")

    append_log(rag_dir, "rag-init", f"dimensions={dimensions} vocab={vocab_axes}", "ok")
    print(f"RAG initialized at {rag_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
